name: animal_id
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  camera: 0.4.3+2
  tflite: 1.0.1
  flutter_redux: ^0.5.2
  path: 1.6.2
  audioplayers: 0.10.1
  image_picker: ^0.4.10
  image: ^2.0.5
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/models/detection/model.tflite
    - assets/models/detection/labels.txt
    - assets/models/detection/info.txt
    - assets/models/classification/model.tflite
    - assets/models/classification/labels.txt
    - assets/models/classification/dogs.txt
    - assets/sounds/save.wav
    # misc
    - assets/images/misc/kennel.png
    - assets/images/misc/silhouette.png
    - assets/images/misc/unknown_dog.jpg
    # dogs
    - assets/images/dogs/001.jpg
    - assets/images/dogs/002.jpg
    - assets/images/dogs/003.jpg
    - assets/images/dogs/004.jpg
    - assets/images/dogs/005.jpg
    - assets/images/dogs/006.jpg
    - assets/images/dogs/007.jpg
    - assets/images/dogs/008.jpg
    - assets/images/dogs/009.jpg
    - assets/images/dogs/010.jpg
    - assets/images/dogs/011.jpg
    - assets/images/dogs/012.jpg
    - assets/images/dogs/013.jpg
    - assets/images/dogs/014.jpg
    - assets/images/dogs/015.jpg
    - assets/images/dogs/016.jpg
    - assets/images/dogs/017.jpg
    - assets/images/dogs/018.jpg
    - assets/images/dogs/019.jpg
    - assets/images/dogs/020.jpg
    - assets/images/dogs/021.jpg
    - assets/images/dogs/022.jpg
    - assets/images/dogs/023.jpg
    - assets/images/dogs/024.jpg
    - assets/images/dogs/025.jpg
    - assets/images/dogs/026.jpg
    - assets/images/dogs/027.jpg
    - assets/images/dogs/028.jpg
    - assets/images/dogs/029.jpg
    - assets/images/dogs/030.jpg
    - assets/images/dogs/031.jpg
    - assets/images/dogs/032.jpg
    - assets/images/dogs/033.jpg
    - assets/images/dogs/034.jpg
    - assets/images/dogs/035.jpg
    - assets/images/dogs/036.jpg
    - assets/images/dogs/037.jpg
    - assets/images/dogs/038.jpg
    - assets/images/dogs/039.jpg
    - assets/images/dogs/040.jpg
    - assets/images/dogs/041.jpg
    - assets/images/dogs/042.jpg
    - assets/images/dogs/043.jpg
    - assets/images/dogs/044.jpg
    - assets/images/dogs/045.jpg
    - assets/images/dogs/046.jpg
    - assets/images/dogs/047.jpg
    - assets/images/dogs/048.jpg
    - assets/images/dogs/049.jpg
    - assets/images/dogs/050.jpg
    - assets/images/dogs/051.jpg
    - assets/images/dogs/052.jpg
    - assets/images/dogs/053.jpg
    - assets/images/dogs/054.jpg
    - assets/images/dogs/055.jpg
    - assets/images/dogs/056.jpg
    - assets/images/dogs/057.jpg
    - assets/images/dogs/058.jpg
    - assets/images/dogs/059.jpg
    - assets/images/dogs/060.jpg
    - assets/images/dogs/061.jpg
    - assets/images/dogs/062.jpg
    - assets/images/dogs/063.jpg
    - assets/images/dogs/064.jpg
    - assets/images/dogs/065.jpg
    - assets/images/dogs/066.jpg
    - assets/images/dogs/067.jpg
    - assets/images/dogs/068.jpg
    - assets/images/dogs/069.jpg
    - assets/images/dogs/070.jpg
    - assets/images/dogs/071.jpg
    - assets/images/dogs/072.jpg
    - assets/images/dogs/073.jpg
    - assets/images/dogs/074.jpg
    - assets/images/dogs/075.jpg
    - assets/images/dogs/076.jpg
    - assets/images/dogs/077.jpg
    - assets/images/dogs/078.jpg
    - assets/images/dogs/079.jpg
    - assets/images/dogs/080.jpg
    - assets/images/dogs/081.jpg
    - assets/images/dogs/082.jpg
    - assets/images/dogs/083.jpg
    - assets/images/dogs/084.jpg
    - assets/images/dogs/085.jpg
    - assets/images/dogs/086.jpg
    - assets/images/dogs/087.jpg
    - assets/images/dogs/088.jpg
    - assets/images/dogs/089.jpg
    - assets/images/dogs/090.jpg
    - assets/images/dogs/091.jpg
    - assets/images/dogs/092.jpg
    - assets/images/dogs/093.jpg
    - assets/images/dogs/094.jpg
    - assets/images/dogs/095.jpg
    - assets/images/dogs/096.jpg
    - assets/images/dogs/097.jpg
    - assets/images/dogs/098.jpg
    - assets/images/dogs/099.jpg
    - assets/images/dogs/100.jpg
    - assets/images/dogs/101.jpg
    - assets/images/dogs/102.jpg
    - assets/images/dogs/103.jpg
    - assets/images/dogs/104.jpg
    - assets/images/dogs/105.jpg
    - assets/images/dogs/106.jpg
    - assets/images/dogs/107.jpg
    - assets/images/dogs/108.jpg
    - assets/images/dogs/109.jpg
    - assets/images/dogs/110.jpg
    - assets/images/dogs/111.jpg
    - assets/images/dogs/112.jpg
    - assets/images/dogs/113.jpg
    - assets/images/dogs/114.jpg
    - assets/images/dogs/115.jpg
    - assets/images/dogs/116.jpg
    - assets/images/dogs/117.jpg
    - assets/images/dogs/118.jpg
    - assets/images/dogs/119.jpg
    - assets/images/dogs/120.jpg
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
